export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
      },
      width: {
        "1/7": "14.2857142",
        "1/9": "11.111111",
        "1/10": "10",
      },
      height: {
        "1/7": "14.2857142",
        "1/9": "11.111111",
        "1/10": "10",
      },

      colors: {
        lightMode: {
          layoutColor: "#f9fafb",
          itemBackgroundColor: "#f3f4f6",
          sidebarColor: "#FFFFFF",
          sidebarItemIconColor: "#9d174d",
          sidebarItemColorHover: "#fdf2f8",
          sidebarItemTextColor: "#4b5563",
          sidebarItemGradientFrom: "#fbcfe8",
          sidebarItemGradientTo: "#fce7f3",
          sidebarBubbleColor: "#f472b6",
          topBarColor: "#FFFFFF",
          topBarItemTextColor: "black",
          tableBackgroundColor: "white",
          evenRowTable: "#ffffff",
          oddRowTable: "#f5f5f5",
          hoverRowTable: "#fce7f3",
          selectedTableRow: "#fbcfe8",
          tableHeaderBackgroundColor: "#fff",
          borderColor: "#d1d5db",
          overlayBackgroundColor: "#fff",
        },
        lightMode2: {
          sidebarBubbleColor: "#c084fc",
        },
        // darkMode: {
        //   layoutColor: "#0A0A0A",
        //   itemBackgroundColor: "#0F0F0F",
        //   sidebarColor: "#111111",
        //   sidebarItemIconColor: "#831843",
        //   sidebarItemColorHover: "#f472b6",
        //   sidebarItemTextColor: "#6b7280",
        // sidebarItemGradientFrom: "#831843",
        // sidebarItemGradientTo: "#500724",
        //   sidebarBubbleColor: "#be185d",
        //   topBarColor: "#111111",
        //   topBarItemTextColor: "#6b7280",
        //   tableBackgroundColor: "#0d0d0d",
        //   evenRowTable: "#0D0D0D",
        //   oddRowTable: "#111111",
        //   hoverRowTable: "#151515",
        //   selectedTableRow: "#1E1E1E",
        //   tableHeaderBackgroundColor: "#0D0D0D",
        //   borderColor: "#1f2937",
        //   overlayBackgroundColor: "#0A0A0A",
        // },

        darkMode: {
          layoutColor: "#121212",
          itemBackgroundColor: "#1E1E1E",
          sidebarColor: "#1A1A1A",
          sidebarItemIconColor: "#ec4899",
          sidebarItemColorHover: "#FFB6B0",
          sidebarItemTextColor: "#D0D0D0",
          sidebarItemGradientFrom: "#831843",
          sidebarItemGradientTo: "#500724",
          sidebarBubbleColor: "#FF6F61",
          topBarColor: "#1A1A1A",
          topBarItemTextColor: "#D0D0D0",
          tableBackgroundColor: "#1E1E1E",
          evenRowTable: "#222222",
          oddRowTable: "#1E1E1E",
          hoverRowTable: "#333333",
          selectedTableRow: "#444444",
          tableHeaderBackgroundColor: "#1A1A1A",
          borderColor: "#2C2C2C",
          overlayBackgroundColor: "#121212",
        },
      },
    },
  },
  plugins: [],
};
