export const getPatientsData = () => {
  return [
    {
      userForename: "Efrain",
      userSurname: "Stein",
      userEmail: "efrain.stein@gmail.com",
      userPhoneNumber: "efrainsteinPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "efrainsteinaddress",
      userEncryptedPassword: "efrainsteinpassword",
    },
    {
      userForename: "Jude",
      userSurname: "Lozano",
      userEmail: "jude.lozano@gmail.com",
      userPhoneNumber: "judelozanoPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "judelozanoaddress",
      userEncryptedPassword: "judelozanopassword",
    },
    {
      userForename: "Royal",
      userSurname: "Thomas",
      userEmail: "royal.thomas@gmail.com",
      userPhoneNumber: "royalthomasPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "royalthomasaddress",
      userEncryptedPassword: "royalthomaspassword",
    },
    {
      userForename: "Jaime",
      userSurname: "Kline",
      userEmail: "jaime.kline@gmail.com",
      userPhoneNumber: "jaimeklinePhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "jaimeklineaddress",
      userEncryptedPassword: "jaimeklinepassword",
    },
    {
      userForename: "Christy",
      userSurname: "Rivera",
      userEmail: "christy.rivera@gmail.com",
      userPhoneNumber: "christyriveraPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "christyriveraaddress",
      userEncryptedPassword: "christyriverapassword",
    },
    {
      userForename: "Shana",
      userSurname: "Bender",
      userEmail: "shana.bender@gmail.com",
      userPhoneNumber: "shanabenderPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "shanabenderaddress",
      userEncryptedPassword: "shanabenderpassword",
    },
    {
      userForename: "Elijah",
      userSurname: "Clarke",
      userEmail: "elijah.clarke@gmail.com",
      userPhoneNumber: "elijahclarkePhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "elijahclarkeaddress",
      userEncryptedPassword: "elijahclarkepassword",
    },
    {
      userForename: "Joy",
      userSurname: "Roberts",
      userEmail: "joy.roberts@gmail.com",
      userPhoneNumber: "joyrobertsPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "joyrobertsaddress",
      userEncryptedPassword: "joyrobertspassword",
    },
    {
      userForename: "Sammy",
      userSurname: "Long",
      userEmail: "sammy.long@gmail.com",
      userPhoneNumber: "sammylongPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "sammylongaddress",
      userEncryptedPassword: "sammylongpassword",
    },
    {
      userForename: "Geneva",
      userSurname: "Bentley",
      userEmail: "geneva.bentley@gmail.com",
      userPhoneNumber: "genevabentleyPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "genevabentleyaddress",
      userEncryptedPassword: "genevabentleypassword",
    },
    {
      userForename: "Andre",
      userSurname: "Graves",
      userEmail: "andre.graves@gmail.com",
      userPhoneNumber: "andregravesPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "andregravesaddress",
      userEncryptedPassword: "andregravespassword",
    },
    {
      userForename: "Taylor",
      userSurname: "Browning",
      userEmail: "taylor.browning@gmail.com",
      userPhoneNumber: "taylorbrowningPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "taylorbrowningaddress",
      userEncryptedPassword: "taylorbrowningpassword",
    },
    {
      userForename: "Jame",
      userSurname: "Dougherty",
      userEmail: "jame.dougherty@gmail.com",
      userPhoneNumber: "jamedoughertyPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "jamedoughertyaddress",
      userEncryptedPassword: "jamedoughertypassword",
    },

    {
      userForename: "Lolita",
      userSurname: "Daniel",
      userEmail: "lolita.daniel@gmail.com",
      userPhoneNumber: "lolitadanielPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "lolitadanieladdress",
      userEncryptedPassword: "lolitadanielpassword",
    },
    {
      userForename: "Gavin",
      userSurname: "Strong",
      userEmail: "gavin.strong@gmail.com",
      userPhoneNumber: "gavinstrongPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "gavinstrongaddress",
      userEncryptedPassword: "gavinstrongpassword",
    },
    {
      userForename: "Roland",
      userSurname: "Tran",
      userEmail: "roland.tran@gmail.com",
      userPhoneNumber: "rolandtranPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "rolandtranaddress",
      userEncryptedPassword: "rolandtranpassword",
    },
    {
      userForename: "Garland",
      userSurname: "Cross",
      userEmail: "garland.cross@gmail.com",
      userPhoneNumber: "garlandcrossPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "garlandcrossaddress",
      userEncryptedPassword: "garlandcrosspassword",
    },
    {
      userForename: "Maura",
      userSurname: "Lynch",
      userEmail: "maura.lynch@gmail.com",
      userPhoneNumber: "mauralynchPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "mauralynchaddress",
      userEncryptedPassword: "mauralynchpassword",
    },
    {
      userForename: "Lyman",
      userSurname: "Vaughan",
      userEmail: "lyman.vaughan@gmail.com",
      userPhoneNumber: "lymanvaughanPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "lymanvaughanaddress",
      userEncryptedPassword: "lymanvaughanpassword",
    },
    {
      userForename: "Enoch",
      userSurname: "Hughes",
      userEmail: "enoch.hughes@gmail.com",
      userPhoneNumber: "enochhughesPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "enochhughesaddress",
      userEncryptedPassword: "enochhughespassword",
    },
    {
      userForename: "Raul",
      userSurname: "Brown",
      userEmail: "raul.brown@gmail.com",
      userPhoneNumber: "raulbrownPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "raulbrownaddress",
      userEncryptedPassword: "raulbrownpassword",
    },
    {
      userForename: "Shane",
      userSurname: "Zamora",
      userEmail: "shane.zamora@gmail.com",
      userPhoneNumber: "shanezamoraPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "shanezamoraaddress",
      userEncryptedPassword: "shanezamorapassword",
    },
    {
      userForename: "Jeanette",
      userSurname: "Lloyd",
      userEmail: "jeanette.lloyd@gmail.com",
      userPhoneNumber: "jeanettelloydPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "jeanettelloydaddress",
      userEncryptedPassword: "jeanettelloydpasword",
    },
    {
      userForename: "Katrina",
      userSurname: "Braun",
      userEmail: "katrina.braun@gmail.com",
      userPhoneNumber: "katrinabraunPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "katrinabraunaddress",
      userEncryptedPassword: "katrinabraunpassword",
    },
    {
      userForename: "Gilda",
      userSurname: "Randolph",
      userEmail: "gilda.randolph@gmail.com",
      userPhoneNumber: "gildarandolphPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "gildarandolphaddress",
      userEncryptedPassword: "gildarandolphpassword",
    },
    {
      userForename: "Gwen",
      userSurname: "Meyer",
      userEmail: "gwen.meyer@gmail.com",
      userPhoneNumber: "gwenmeyerPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "gwenmeyeraddress",
      userEncryptedPassword: "gwenmeyerpassword",
    },
    {
      userForename: "Cecelia",
      userSurname: "Shelton",
      userEmail: "cecelia.shelton@gmail.com",
      userPhoneNumber: "ceceliasheltonPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "ceceliasheltonaddress",
      userEncryptedPassword: "ceceliasheltonpassword",
    },
  ];
};

export const getDoctorData = () => {
  return [
    {
      userForename: "Delia",
      userSurname: "David",
      userEmail: "delia.david@gmail.com",
      userPhoneNumber: "deliadavidPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "deliadavidaddress",
      userEncryptedPassword: "deliadavidpassword",
    },

    {
      userForename: "Kimberley",
      userSurname: "Burns",
      userEmail: "kimberley.burns@gmail.com",
      userPhoneNumber: "kimberleyburnsPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "kimberleyburnsaddress",
      userEncryptedPassword: "kimberleyburnspassword",
    },
    {
      userForename: "Timmy",
      userSurname: "Brewer",
      userEmail: "timmy.brewer@gmail.com",
      userPhoneNumber: "timmybrewerPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "timmybreweraddress",
      userEncryptedPassword: "timmybrewerpassword",
    },
    {
      userForename: "Brooke",
      userSurname: "Torres",
      userEmail: "brooke.torres@gmail.com",
      userPhoneNumber: "brooketorresPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "brooketorresaddress",
      userEncryptedPassword: "brooketorrespassword",
    },
    {
      userForename: "Sharron",
      userSurname: "Gibson",
      userEmail: "sharron.gibson@gmail.com",
      userPhoneNumber: "sharrongibsonPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "sharrongibsonaddress",
      userEncryptedPassword: "sharrongibsonpassword",
    },
    {
      userForename: "Daron",
      userSurname: "Butler",
      userEmail: "daron.butler@gmail.com",
      userPhoneNumber: "daronbutlerPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "daronbutleraddress",
      userEncryptedPassword: "daronbutlerpassword",
    },
    {
      userForename: "Rosalind",
      userSurname: "Rose",
      userEmail: "rosalind.rose@gmail.com",
      userPhoneNumber: "rosalindrosePhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "rosalindroseaddress",
      userEncryptedPassword: "rosalindrosepassword",
    },
    {
      userForename: "Rhoda",
      userSurname: "Cherry",
      userEmail: "rhoda.cherry@gmail.com",
      userPhoneNumber: "rhodacherryPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "rhodacherryaddress",
      userEncryptedPassword: "rhodacherrypassword",
    },
    {
      userForename: "Elinor",
      userSurname: "Russell",
      userEmail: "elinor.russell@gmail.com",
      userPhoneNumber: "elinorrussellPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "elinorrusselladdress",
      userEncryptedPassword: "elinorrussellpassword",
    },
    {
      userForename: "Jeanine",
      userSurname: "Boyer",
      userEmail: "jeanine.boyer@gmail.com",
      userPhoneNumber: "jeanineboyerPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "jeanineboyeraddress",
      userEncryptedPassword: "jeanineboyerpassword",
    },
    {
      userForename: "Aimee",
      userSurname: "Wang",
      userEmail: "aimee.wang@gmail.com",
      userPhoneNumber: "aimeewangPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "aimeewangaddress",
      userEncryptedPassword: "aimeewangpassword",
    },
    {
      userForename: "Tammie",
      userSurname: "Mccullough",
      userEmail: "tammie.mccullough@gmail.com",
      userPhoneNumber: "tammiemcculloughPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "tammiemcculloughaddress",
      userEncryptedPassword: "tammiemcculloughpassword",
    },
    {
      userForename: "Valeria",
      userSurname: "Reese",
      userEmail: "valeria.reese@gmail.com",
      userPhoneNumber: "valeriareesePhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "valeriareeseaddress",
      userEncryptedPassword: "valeriareesepassword",
    },
    {
      userForename: "Mac",
      userSurname: "Rocha",
      userEmail: "mac.rocha@gmail.com",
      userPhoneNumber: "macrochaPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "macrochaaddress",
      userEncryptedPassword: "macrochapassword",
    },
    {
      userForename: "Lisa",
      userSurname: "Vega",
      userEmail: "lisa.vega@gmail.com",
      userPhoneNumber: "lisavegaPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "lisavegaaddress",
      userEncryptedPassword: "lisavegapassword",
    },
    {
      userForename: "Teresa",
      userSurname: "Nguyen",
      userEmail: "teresa.nguyen@gmail.com",
      userPhoneNumber: "teresanguyenPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "teresanguyenaddress",
      userEncryptedPassword: "teresanguyenpassword",
    },
    {
      userForename: "Jeannine",
      userSurname: "Edwards",
      userEmail: "jeannine.edwards@gmail.com",
      userPhoneNumber: "jeannineedwardsPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "jeannineedwardsaddress",
      userEncryptedPassword: "jeannineedwardspassword",
    },
    {
      userForename: "Abraham",
      userSurname: "Keller",
      userEmail: "abraham.keller@gmail.com",
      userPhoneNumber: "abrahamkellerPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "abrahamkelleraddress",
      userEncryptedPassword: "abrahamkellerpassword",
    },

    {
      userForename: "Garet",
      userSurname: "Ferrell",
      userEmail: "gay.ferrell@gmail.com",
      userPhoneNumber: "gayferrellPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "gayferrelladdress",
      userEncryptedPassword: "gayferrellpassword",
    },
    {
      userForename: "Brian",
      userSurname: "Barker",
      userEmail: "brian.barker@gmail.com",
      userPhoneNumber: "brianbarkerPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "brianbarkeraddress",
      userEncryptedPassword: "brianbarkerpassword",
    },
    {
      userForename: "Rocco",
      userSurname: "Trujillo",
      userEmail: "rocco.trujillo@gmail.com",
      userPhoneNumber: "roccotrujilloPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "roccotrujilloaddress",
      userEncryptedPassword: "roccotrujillopassword",
    },
    {
      userForename: "Cheri",
      userSurname: "Harvey",
      userEmail: "cheri.harvey@gmail.com",
      userPhoneNumber: "cheriharveyPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "female",
      userAddress: "cheriharveyaddress",
      userEncryptedPassword: "cheriharveypassword",
    },
    {
      userForename: "Alonso",
      userSurname: "Davis",
      userEmail: "alonso.davis@gmail.com",
      userPhoneNumber: "alonsodavisPhoneNumber",
      userDateOfBirth: "1234-01-01",
      userGender: "male",
      userAddress: "alonsodavisaddress",
      userEncryptedPassword: "alonsodavispassword",
    },
  ];
};
